# Generated by Django 4.2.11 on 2024-04-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('masterCategory', models.CharField(max_length=50)),
                ('subCategory', models.CharField(max_length=50)),
                ('articleType', models.CharField(max_length=50)),
                ('baseColour', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('usage', models.CharField(max_length=50)),
                ('productDisplayName', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('file_found', models.BooleanField(default=False)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_informations', to='products.products')),
            ],
        ),
    ]
