# Generated by Django 4.2.11 on 2024-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_productsinformation_alter_products_id'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='ProductsInformation',
        # ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(max_length=255, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
