# Generated by Django 4.2.11 on 2024-04-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinformation',
            name='productDisplayName',
            field=models.CharField(max_length=150),
        ),
    ]
