# Generated by Django 4.2.11 on 2024-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productsinformation_productdisplayname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinformation',
            name='products_id',
        ),
        migrations.AlterField(
            model_name='productsinformation',
            name='articleType',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productsinformation',
            name='baseColour',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productsinformation',
            name='gender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productsinformation',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productsinformation',
            name='masterCategory',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productsinformation',
            name='productDisplayName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productsinformation',
            name='season',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productsinformation',
            name='subCategory',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productsinformation',
            name='usage',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productsinformation',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='productsinformation',
            table='products_information',
        ),
    ]
